import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import ToastContainer from "./components/UI/Toast";
import "./index.css";

// Register the service worker generated by vite-plugin-pwa
if ("serviceWorker" in navigator && import.meta.env.PROD) {
  window.addEventListener("load", () => {
    import("virtual:pwa-register")
      .then(({ registerSW }) => {
        registerSW({
          immediate: true,
          onNeedRefresh() {
            console.info("[PWA] Yeni sürüm mevcut, yenileme gerekli");
          },
          onOfflineReady() {
            console.info("[PWA] Çevrimdışı kullanıma hazır");
          },
        });
      })
      .catch(() => {
        // vite-plugin-pwa not loaded in this environment — ignore
      });
  });
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
      <ToastContainer />
    </BrowserRouter>
  </React.StrictMode>
);
